version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./App.Web/dist:/usr/share/nginx/html
  api:
    build: App.API
    ports:
      - 3333:3333
    restart: always
